.gitignore
Makefile
app/templates/home.html

Cleaner and better aligned Makefile.
Valum-0.1.gir ends in the build directory.
build directory that contains generated files is ignored.

Generated libraries and executables follow better naming conventions.

---

app/app.vala
src/route.vala
src/router.vala

It is cleaner to use a catch-all route to handle 404 instead of a
default request.

Catch-all route instead of default_request signal.

---

app/app.vala
app/templates/home.html
docs/route.md
src/request.vala
src/route.vala
src/router.vala

This replace the _regex-by-default_ routing system with a more powerful system based on callback.
Instead of having `Regex` that matches `Request`, a `RequestMatcher` callback is applied on the user request and populate its parameters if successful.
This design can allow user to create route that matches based on any kind of condition (eg. database available, user is an administrator, etc...)
The Route.from_rule still uses Regex, but it captures it into a `RequestMatcher` callback in that fashion:
```vala
this.matcher = (req) => {
if (regex.match (req.path, 0, out match_info)) {
// populate the request parameters
}
}
```
This design benefits from the last_matchinfo optimization I did to improve the number of regex matches as it will match and populate in one step. `fire` will only call …

Replaces Regex by Request matcher pattern

---

src/route.vala
src/router.vala
src/vsgi/fastcgi.vala
src/vsgi/request.vala
src/vsgi/response.vala
src/vsgi/soup.vala
tests/tests.vala
tests/valum/test_route.vala

This PR replaces all use of Gee data structure by more adapted GLib ones for the framework internals.
This is especially important for VSGI specification as it has to have a minimum of dependencies. libsoup is like just enough.
I have also improved the data structure over the framework
- we often traverse and append to routes in `routes` `HashTable`, so it uses a `Queue`
- scopes uses a real stack (double-ended queue)
- `HashTable` implementation of GLib is very efficient
The main idea here is to minimize our dependencies and use more efficient data structure for the framework.

Gee only for examples

---

src/view.vala
tests/data/ctpl-template.html
tests/test_route.vala
tests/test_router.vala
tests/test_view.vala
tests/tests.vala
wscript

Tests for all Router built-in HTTP methods and ServerError thrown in a handler.
Test for creating a Route from a rule using an undefined type. Since it's
requiring a subprocess trap, it is conditionnaly built with glib (>=2.38).
Tests for View were added:
- tests for view creation from string, path and stream
- test for pushing a collection containing an unknown type
- test for pushing string with push_value
- test for push an unknown type with push_value
Removes non-working types from push_value, it seems like typeof does not work on
primitives or array of primitives.

Tests for Router, Route and View.

---

docs/hacking.rst
docs/index.rst

Covers building Valum without installing by exporting LD_LIBRARY_PATH to the
build folder.
Highlights coding conventions.
Explain how the coverage is measured and how one can identify uncovered region
in order to supply relevant tests.

Covers 'Hacking Valum' in the documentation.

---

docs/route.rst
docs/router.rst
examples/app/app.vala
src/route.vala
src/router.vala
tests/test_route.vala
tests/tests.vala

The rule used will automatically default to "<any:path>", according to the
definition of the any by the router. The matched path is made available in the
request parameters under the "path" key.
Since the router is principally rule-oriented, this feature allow a much better
integration of middlewares and setup operations.
Adds a test to ensure it works properly.
Documents the functionnality.

Route with a null rule will catch all request paths.

---

docs/cookies.rst
docs/index.rst
docs/vsgi/request.rst
docs/vsgi/response.rst
examples/app/app.vala
src/cookies.vala
src/router.vala
src/vsgi/request.vala
src/vsgi/response.vala
tests/test_cookies.vala
tests/tests.vala

Cookies are stored in HTTP headers, so it's not really relevant for VSGI
to provide helpers for them since it aims to be a minimal protocol.
Instead, the code to extract cookies is moved in 'cookies_from_headers'
function to provide equivalent parsing capabilities. The functions
provided by libsoup-2.4 for that purpose takes a Soup.Message as
parameter, which is not common to all VSGI implementations.

Removes cookies from VSGI.

---

docs/recipes/json.rst
docs/router.rst
src/router.vala
tests/test_router.vala
tests/tests.vala

This solve the kind of situation where next has to be invoked in an async callback, but the exception handling is not available.
```vala
app.get ("", (req, res, next) => {
res.write_async ("Hello world!".data, Priority.DEFAULT, null, (obj, result) => {
// the 404 will be properly handled
app.invoke (req, res, next);
});
});
app.all (null, (req, res) => {
throws ClientError.NOT_FOUND ("");
});
app.status (404, (req, res) => {
// produce a 404 page...
});
```
It has the signature of a `HandlerCallback`, so I am pretty sure that it can be useful as a handling middleware.
I will write some tests and documentation and merge the changes.

Provides invoke in the Router to execute an arbitrary NextCallback

---

docs/router.rst
examples/app/app.vala
src/route.vala
src/router.vala
tests/test_route.vala
tests/test_router.vala
tests/tests.vala

This feature can produce a handling sequence by reusing the same matching callback for multiple handlers.
The `Route` has to know which HTTP method it is declared with, so its constructors has been slightly modified to require that information. It might even be possible to take rid of the method table since it is already in the route, but that would be for later if we have to rework the `Router` internals.
```vala
app.get ("", (req, res, next) => {
next ();
}).then ((req, res) => {
// ...
});

[WIP] Reuses a matcher with then in Route.

---

docs/installation.rst
src/route.vala
src/router.vala
tests/test_router.vala
wscript

Since the HTTP method have been moved to Route, there's no point to
maintain a mapping of methods to route queues in the Router.
No need to check if the mapping contains the method anymore, so the code
is much less complex.
Route method can be 'null' if matching the method does not apply. This
is used for status-based routes.
Modify the order of methods in 'Allow' header as they will respect the
order of declaration in the code.

Invert routing process

---

src/vsgi-scgi.vala

On using the --port switch with a SCGI Server instance, the following
assertion error gets triggered:
```
(zervige:23094): GLib-CRITICAL **: g_variant_get_int16: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT16)' failed
```
This patch gets the int32 and casts to uint16

Fix port command-line parsing in VSGI.SCGI.Server

---

docs/vsgi/request.rst
examples/app/app.vala
src/vsgi-request.vala
src/vsgi-soup.vala

This feature provide `flatten` and `flatten_async` in `Request` to avoid the redundant and error-prone request body flattening.
The correct way to accumulate an `InputStream` have many drawbacks:
- the stream must be spliced into a `MemoryOutputStream`
- the `MemoyOutputStream` must be explicitly closed before calling `get_data`
- the data buffer size must be set from the `MemoryOutputStream`
- a fixed-size buffer can be used if the content length is known
Flattening could also be used for parts in a multipart message (see #81)

Provide 'flatten' and 'flatten_async' in  Request

---

wscript

It works, but there's some mix of c and vala sources, so the coverage value is not really representative.

Adds the '--debug' flag to produce coverage data from the Vala sources.

---

docs/application.rst
docs/redirection-and-error.rst
docs/router.rst
examples/app/app.vala
examples/fastcgi/app.vala
examples/memcached/app.vala
examples/scgi/app.vala
src/valum-context.vala
src/valum-route.vala
src/valum-router.vala
src/valum-server-sent-events.vala
src/valum.vala
src/vsgi-request.vala
tests/cgi-test.vala
tests/fastcgi-test.vala
tests/negociate-test.vala
tests/route-test.vala
tests/router-test.vala
tests/soup-test.vala
tests/tests.vala

The context provide a hierarchical mapping of states shared among handlers. It is possible to access the parent context.
```vala
var context = new Context ();
var context_with_parent = new Context.with_parent (context);
```
All operations are recursively applied. If a key is missing in the current context, it is retrieved in its parent.
```vala
app.use ((req, res, next, context) => {
context["id"] = "6";
next (req, res);
});
app.get ("user/<int:id>", (req, res, next, context) => {
var user_id = context["id"].get_string ();
context.parent["id"]; // refers to '6'
});
```
It completely replace `Request.params`, which has been removed.

Provide a routing context instead of a stack

---

.travis.yml
docs/installation.rst
src/valum/valum-router.vala
src/vsgi-fastcgi/vsgi-fastcgi.vala
src/vsgi-http/vsgi-http.vala
src/vsgi-http/wscript
src/vsgi/wscript
tests/cgi-test.vala
tests/chunked-encoder-test.vala
tests/negociate-test.vala
tests/route-test.vala
tests/router-test.vala
tests/server-sent-events-test.vala
tests/subdomain-test.vala
tests/wscript
wscript

I would be great to lower the requirements for `valac` down to something like 0.14 since it's what's available on Precise.

Enable --fatal-warnings and fix them

---

docs/application.rst
docs/getting-started.rst
docs/hacking.rst
docs/recipes/persistence.rst
docs/recipes/scripting.rst
docs/router.rst
docs/vsgi/converters.rst
docs/vsgi/filters.rst
docs/vsgi/request.rst
docs/vsgi/response.rst
examples/api-interaction/app.vala
examples/app/app.vala
examples/cgi/app.vala
examples/fastcgi/app.vala
examples/lua/app.vala
examples/markdown/app.vala
examples/memcached/app.vala
examples/modular-app/admin-router.vala
examples/modular-app/app.vala
examples/modular-app/user-router.vala
examples/scgi/app.vala
src/vsgi/vsgi-response.vala

I'm wondering if the UTF-8 expansion should set the `charset` parameter for the `Content-Type` header.
The documentation should be updated as well.
Otherwise, it's ready to merge!

Provide expansion utilities to write the response body

---

README.md
docs/application.rst
docs/getting-started.rst
docs/recipes/json.rst
docs/recipes/persistence.rst
docs/recipes/scripting.rst
docs/redirection-and-error.rst
docs/route.rst
docs/router.rst
docs/vsgi/request.rst
docs/vsgi/response.rst
examples/api-interaction/app.vala
examples/app/app.vala
examples/cgi/app.vala
examples/fastcgi/app.vala
examples/json/app.vala
examples/lua/app.vala
examples/markdown/app.vala
examples/memcached/app.vala
examples/modular-app/admin-router.vala
examples/modular-app/app.vala
examples/modular-app/user-router.vala
examples/scgi/app.vala
src/valum/valum-router.vala
tests/router-test.vala
tests/server-sent-events-test.vala

It's semantically better and has a few advantages:
- easier to understand as it correspond to the actual request URI
- scoping does not add an ending slash anymore
However, the slash must be explicitly given for rules, regular expressions and scopes.

router: Enforce explicit leading slash

---

docs/middlewares/basepath.rst
docs/middlewares/index.rst
examples/app/app.vala
src/valum/valum-basepath.vala
tests/basepath-test.vala
tests/wscript

The `basepath` middleware provide a way of stripping a path prefix, which is very handy when composing routers.
- strip the basepath on incoming requests
- rewrite thrown error that use the message as `Location` header
- restore the original path if `next` is called while forwarding
@Bob131 feedback?

Basepath middleware

---

docs/middlewares/decode.rst
docs/middlewares/index.rst
examples/app/app.vala
src/valum/valum-decode.vala
tests/decode-test.vala
tests/tests.vala

Two really useful middlewares to decode applied encoding and content charset.
It will require some documentation and tests. The logic is quite tricky, especially for `decode` as remaining encodings are reversed back in the headers.
I couldn't find anything more appropriate than `501 Not Implemented` to indicate the lack of support for an encoding or charset.
The typical use case is on the top of an app or for an upload processing:
```vala
app.use (decode ()));
app.post ("document", decode ())
.then ((req, res) => {
var doc = req.flatten_bytes ();
});
```
The squash integration must be opt-in with fallback on the basic converters.

Middleware to decode encoding and charset

---

docs/middlewares/index.rst
docs/middlewares/static.rst
docs/recipes/static-resource.rst
examples/app/app.vala
examples/app/templates/home.html
examples/fastcgi/app.vala
examples/fastcgi/lighttpd.conf
src/valum/valum-static.vala

These are basic middlewares able to serve content from `GLib.File` and `GLib.Resource`. It supports `ETag`.
It could eventually be coupled with a middleware that supports HTTP caching for optimal performances.
With GVFS, it is even possible to serve remote files using various protocols.
There's a few thing to finish, mainly documentation and tests, before it can be merged.

Introduces middlewares for serving static content.

---

docs/vsgi/response.rst
examples/app/app.vala
src/vsgi/servers/vsgi-http.vala
src/vsgi/vsgi-cgi.vala
src/vsgi/vsgi-mock.vala
src/vsgi/vsgi-response.vala
tests/response-test.vala

Some protocols like 'HTTP/2.0' use different channels for sending headers and body resulting in the possibility of having parts of the body emitted while not all headers are sent. This is while splitting `Response.write_head` is very convenient.
Automatically calling a writer should be implementation-specific, so we don't write headers when the body is first accessed.
`Response.head_written` is replaced by a flag covering the following conditions:
- status line written
- headers written
It's not possible to reliably know when the body has been written.
It's handy to have a final status line but not yet headers, especially if one wants to generate headers based on a specific status.
```vala
res.wrote_status_line.connect (() => {
// status line is final
if (res.is_cacheable ()) { …
```

Split 'write_head' into 'write_status_line' and 'write_headers'

---

.travis.yml
examples/memcached/vapi/libmemcached.vapi
src/valum/valum-context.vala

It builds with at least `0.26`, which is pretty good already!
For lower versions provided on Ubuntu 14.04:
- `0.22` has older VAPIs for `gio-2.0` so more preprocessor directives would be required
- `0.24` produce a SEGFAULT #167 
Tests for the FastCGI and `SocketListenerServer` servers should use a random open port because they fail for using `3003`.

Build with multiple versions of 'valac'

---

examples/app/app.vala
examples/app/templates/home.html
meson.build
src/valum/meson.build
src/valum/valum-multipart.vala
src/vsgi/meson.build
src/vsgi/vsgi-multipart-input-stream.vala
src/vsgi/vsgi-multipart-output-stream.vala
tests/data/multipart/simple-message
tests/meson.build
tests/multipart-test.vala

The multipart streams provided by libsoup-2.4 require a `Soup.Message` instance which is not common to all VSGI implementations.
This PR provides implementation for `MultipartInputStream` and `MultipartOutputStream` that are similar to what libsoup-2.4 already provides, but adapted to what VSGI is based on.
Implementation reference: http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

Multipart streams

---

src/valum/valum-content-negotiation.vala
src/valum/valum-server-sent-events.vala
src/valum/valum-static.vala
src/vsgi/vsgi-cookie-utils.vala

This brings all of the generated namespaces to the same version. No Gir or Typelib is generated so it's still not possible to create a Typelib for a library that has Valum public symbols.

updated all gir_version attributes to 0.4

---

.editorconfig
src/vsgi/servers/meson.build
src/vsgi/servers/vsgi-fastcgi-input-stream.c
src/vsgi/servers/vsgi-fastcgi-input-stream.h
src/vsgi/servers/vsgi-fastcgi-internal.vapi
src/vsgi/servers/vsgi-fastcgi-output-stream.c
src/vsgi/servers/vsgi-fastcgi-output-stream.h
src/vsgi/servers/vsgi-fastcgi.vala

The current implementation has non-existent error handling due to missing return-value-on-error semantic in Vala.

vsgi: Rewrite FastCGI I/O streams in C (fix #171)
